---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ11N16" #see SAP Continuous Integration and Delivery service for more build tool version options
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Additional Unit Tests:
    npmExecuteScripts: true
  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.jp10.hana.ondemand.com"
    cfOrg: "dpedev"
    cfSpace: "dev"
    cfAppName: "app"
    cfCredentialsId: "deploy-to-cf"
    deployType: "standard"
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.jp10.hana.ondemand.com"
    cfOrg: "dpedev"
    cfSpace: "dev"
    cfAppName: "app"
    cfCredentialsId: "deploy-to-cf"
    deployType: "standard"
    tmsUpload: true
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: true
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "qa"
    credentialsId: "tms-sk"
